env:
  browser: true
extends:
  - google
  - 'plugin:vue/essential'
  - '@vue/prettier'
  - '@vue/typescript'
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
rules:
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: false
  '@typescript-eslint/no-object-literal-type-assertion': 'off'
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/indent': 'off'
  prettier/prettier:
    - error
    - endOfLine: lf
      singleQuote: true
      trailingComma: all
  require-jsdoc: 'off'
  new-cap: 'off'
  no-console: warn
