language: node_js
node_js: node
before_deploy: npm run build
deploy:
  provider: firebase
  token:
    secure: CFMRzpBvFFDCReuwXezFKr0RRxhUeprl1Ay9GUf7nXL6Ld1Dtw3XDAIXURXm1sx6fQYIxRHV3PpAkB9DXypDHXO5FUIFVPTD6DzTGldtjgQ/bJzH3y0ApX5v4QEawb0mLkmbkAC5o/pAYFR3hUTgABo7lg8RR+AEDv5Cxqsj+HRctP7dpQAprhhxw0XUVrUDaj34qd1+m5WjzKoUjujK7vWMPPH5Quhp0Lf5fkwVm9LZ40ERsPuyhafnXXo4S+rS5n8mDPGY0mb/568a1DcGgTD7puQZnmPLZOrzEUTjl53HGGpmKcZ5y7odJRxbaxYRg91zFR0XlNf5dMxAk4uTNQ9krlYbxiOO7mxnDYrBIG9JmEU/fPu/qUqrqiin4iTJsMbwgUJlig2M0+znSDcoRpvDuJuUbTVidrwlJLfYng/boiyY+6gQ+qDFPbJt8GFMY3y9CRxnVbh/9jPjf9rPfciXbS0pQNkKDa1MSzCGU6QZjqDbOxR1lZ84Y2vachkQK6nPouJEZUV+I4LUjBenv/6WD55l0thTLqP9qGF5lx7OH2clM5JO/zFbtQBPgUqg0FkaAr7vypGVrN/CxhDAHPzyU4LadisKPi1XJ5Q5aW16ODIsvzaFBVgjepExDNobxPSqefqG63T8HRaQEur7LOItQ9U8OazBLh5F3AVzwwo=
